changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Added
      labels: [feature, enhancement]
    - title: Fixed
      labels: [bug, fix]
    - title: Changed
      labels: [refactor, performance]
    - title: Other
      labels: ["*"]
